name: flutter_async_examples
description: Examples for flutter_async package.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  async_notifier: ^0.5.0
  flutter:
    sdk: flutter
  flutter_async:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
