name: flutter_async
description: Handle async tasks with ease through automatic loading, error handling, and native widget integration.
version: 0.3.1
homepage: https://www.branvier.com

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: