name: flutter_async
description: Handle async tasks with ease through automatic loading, error handling, and native widget integration.
version: 0.6.4
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/flutter_async
topics:
 - async
 - implicitly
 - automatic
 - state

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  animated_value: ^0.0.1
  async_notifier: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:

flutter: