name: flutter_async
description: Handle async tasks with ease through automatic loading, error handling, and native widget integration.
version: 0.10.0
homepage: https://www.branvier.com
repository: https://github.com/arthurbcd/flutter_async
topics:
 - async
 - implicitly
 - implicit
 - automatic
 - state

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  async_notifier: ^0.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: