name: flutter_async
description: A package offers a collection of custom asynchronous widgets that provide the flexibility to build and manipulate data programmatically. These widgets are designed to simplify the process of handling asynchronous operations in your Flutter applications.
version: 0.0.1
homepage: https://www.branvier.com

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mocktail:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: