name: flutter_async
description: Handle async tasks with ease through automatic loading, error handling, and native widget integration.
version: 0.6.2
homepage: https://www.branvier.com

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  animated_value: ^0.0.1
  async_notifier: ^0.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail:

flutter: